# API Configurations
# API Configurations
api.base.url=https://reqres.in

# UI Configurations
ui.amazon.url=https://www.amazon.eg/
browser=chrome
ui.implicit.wait=10

# Amazon Credentials
amazon.phone=01228173546
amazon.password=Om@123456#

# Amazon Address (required on checkout if no default address exists)
amazon.address.fullName=Omar Khaled
amazon.address.phone=01228173546
amazon.address.line1=Nasr City, Street 10, Building 15
amazon.address.city=Cairo
amazon.address.area=Nasr City
amazon.address.building=15